# Generated by Django 4.2.3 on 2023-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_remove_like_disliked_alter_dislike_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
