# Generated by Django 4.2.3 on 2023-07-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
